language: objective-c

matrix:
  include:
    - {osx_image: xcode6.4, env: 'DST="name=iPhone 5s,OS=7.1"'} # sdk 8.4

before_script:
- xcode-select -p
- xcodebuild -version
- xcodebuild -showsdks
- xcrun simctl list
- instruments -s devices

script:
- screencapture test.jpg
- ./imgur.sh test.jpg
- ls /private/tmp/
- ls /tmp/
- ls ~/Library/Logs/CoreSimulator
- export IOS_SIMULATOR_UDID=$(instruments -s devices | grep "iPhone 5s (7.1" | sed -E 's/.*\[([0-9A-F-]+)\].*/\1/g')   # Get the iPhone 5s deviceid
- echo $IOS_SIMULATOR_UDID
- open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
- sleep 30  # Wait 30 seconds
- screencapture test.jpg
- ./imgur.sh test.jpg
- sleep 30  # Wait 30 seconds
#- open ~/Library/Logs/CoreSimulator/CoreSimulator.log
- tail -30 ~/Library/Logs/CoreSimulator/CoreSimulator.log 
- screencapture test.jpg
- ./imgur.sh test.jpg
#- xcodebuild test -scheme TestKVOext -destination "$DST" 

